Add number-based pagination
fcbr/cl-wnbrowser pull request #181
Opened 2017-04-18 21:40 UTC by joaomarcosgris

Solves #116.

2017-04-18 21:53 UTC, arademaker commented
@fcbr I will let you review it right ?

2017-04-19 11:07 UTC, fcbr requested changes
Please make sure the configurable step is taken into account.  You might need to pass it explicitly as a parameter now.

2017-04-19 11:07 UTC, fcbr commented on templates/search-result.tmpl
> +    {for $f in range(max(0, floor($previous/$limit) - 4),
-4 and +5 in the next line are related to the step, no?  Notice that the step is configurable (see method `get-next` in `web-service.lisp`, default is 10).  We should probably pass the step as a parameter and use the parameter as opposed to hardcoding numbers in the template file.

2017-04-19 16:08 UTC, joaomarcosgris commented on templates/search-result.tmpl
> +    {for $f in range(max(0, floor($previous/$limit) - 4),
The hard coded numbers -4 and 5 are related to the number of Pages that is shown to the user and not to the step. I made This decision to show always 5 pages ahead and before the page that is already displayed

2017-04-19 19:30 UTC, arademaker commented
This decision must go in the configuration , not harder code in the template .

2017-04-20 10:53 UTC, fcbr commented on templates/search-result.tmpl
> +    {for $f in range(max(0, floor($previous/$limit) - 4),
Ah, OK.  Please make sure these are also parameterized; it's best to avoid these hardcoded constants.

2017-04-20 19:25 UTC, joaomarcosgris commented
I think that now all the problems are solved.

2017-04-21 12:04 UTC, fcbr approved these changes

2017-04-21 12:05 UTC, merged